services:
  app:
    build: .
    container_name: nest-christmas-presents
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/christmas_presents
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma db push && 
        npx prisma db seed && 
        npm run start:prod
      "

  db:
    image: mysql:8.0
    container_name: nest-christmas-presents-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: nestjs
      MYSQL_PASSWORD: nestjs
      MYSQL_DATABASE: christmas_presents
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local